spring.application.name=orm-learn

# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/orm_learn
spring.datasource.username=root
spring.datasource.password=Dalmariki@1204

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Change Spring Boot port
server.port=8081